local utils = require('azk.utils')
local path  = require('azk.utils.path')

describe("azk.utils.path", function()
  it("should join paths", function()
    assert.are.equal(path.join('foo', '/bar'), "foo/bar")
    assert.are.equal(path.join('foo', 'bar'), "foo/bar")
    assert.are.equal(path.join('foo/', 'bar'), "foo/bar")
    assert.are.equal(path.join('foo/', '/bar'), "foo/bar")
    assert.are.equal(path.join('/foo', '/bar'), "/foo/bar")
    assert.are.equal(path.join('/foo', 'bar'), "/foo/bar")
    assert.are.equal(path.join('/foo/', 'bar'), "/foo/bar")
    assert.are.equal(path.join('/foo/', '/bar'), "/foo/bar")
    assert.are.equal(path.join('foo', '/bar/'), "foo/bar/")
    assert.are.equal(path.join('foo', 'bar/'), "foo/bar/")
    assert.are.equal(path.join('foo/', 'bar/'), "foo/bar/")
    assert.are.equal(path.join('foo/', '/bar/'), "foo/bar/")
  end)

  it("should normalize paths", function()
    assert.are.equal(path.normalize("/foo/.."), "/")
    assert.are.equal(path.normalize("/../foo"), "/foo")
    assert.are.equal(path.normalize("./foo"), "foo")
  end)

  it("should return a dirname", function()
    assert.are.equal(path.dirname('/usr/bin/vim'), '/usr/bin')
    assert.are.equal(path.dirname('/usr/bin/'), '/usr')
    assert.are.equal(path.dirname('/usr/bin'), '/usr')
  end)

  it("should return a basename", function()
    assert.are.equal(path.basename('bar'), 'bar')
    assert.are.equal(path.basename('foo/bar'), 'bar')
    assert.are.equal(path.basename('/'), '')
    assert.are.equal(path.basename('bar.lua'), 'bar.lua')
    assert.are.equal(path.basename('bar.lua', '.lua'), 'bar')
    assert.are.equal(path.basename('bar.lua.js', '.lua'), 'bar.lua.js')
    assert.are.equal(path.basename('.lua', 'lua'), '.')
    assert.are.equal(path.basename('bar', '.lua'), 'bar')
  end)
end)
