#!/usr/bin/env node

// Load path
require.extensions['.conf'] = require.extensions['.json'];
var apptly = require('/root/.aptly.conf');

// App
var express = require('express');
var app     = express();
var server  = require('http').Server(app);

// server as static
var path = require('path');

var fedora_versions = [ "fedora20", "fedora23" ];
for (var fedora_version of fedora_versions) {
  app.use(path.join('/', fedora_version), express.static(
    path.resolve(__dirname, "..", "..", "..", "package", path.join('/', fedora_version))
  ));
}
app.use("/", express.static(path.join(apptly.rootDir, 'public')));

// run
server.listen(process.env.HTTP_PORT || 8080);
